config/routes.rb
TeamTracker::Application.routes.draw do
  resources :team_members

  resources :teams

  resources :contacts

  devise_for :users

  get "home/index"
  get "devise/new"

  resources :users
  
  match 'contacts/:id/edit2' => 'contacts#edit2'
  

  root :to => 'home#index'

end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  attr_accessible :role, :teamID, :userID
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  # GET /team_members
  # GET /team_members.json
  def index
    @team_members = TeamMember.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @team_members }
    end
  end

  # GET /team_members/1
  # GET /team_members/1.json
  def show
    @team_member = TeamMember.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @team_member }
    end
  end

  # GET /team_members/new
  # GET /team_members/new.json
  def new
    @team_member = TeamMember.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @team_member }
    end
  end

  # GET /team_members/1/edit
  def edit
    @team_member = TeamMember.find(params[:id])
  end

  # POST /team_members
  # POST /team_members.json
  def create
    @team_member = TeamMember.new(params[:team_member])

    respond_to do |format|
      if @team_member.save
        format.html { redirect_to @team_member, notice: 'Team member was successfully created.' }
        format.json { render json: @team_member, status: :created, location: @team_member }
      else
        format.html { render action: "new" }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /team_members/1
  # PUT /team_members/1.json
  def update
    @team_member = TeamMember.find(params[:id])

    respond_to do |format|
      if @team_member.update_attributes(params[:team_member])
        format.html { redirect_to @team_member, notice: 'Team member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_members/1
  # DELETE /team_members/1.json
  def destroy
    @team_member = TeamMember.find(params[:id])
    @team_member.destroy

    respond_to do |format|
      format.html { redirect_to team_members_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/team_members/_form.html.erb
<%= form_for(@team_member) do |f| %>
  <% if @team_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@team_member.errors.count, "error") %> prohibited this team_member from being saved:</h2>

      <ul>
      <% @team_member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :teamID %><br />
    <%= f.number_field :teamID %>
  </div>
  <div class="field">
    <%= f.label :userID %><br />
    <%= f.number_field :userID %>
  </div>
  <div class="field">
    <%= f.label :role %><br />
    <%= f.number_field :role %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/team_members/edit.html.erb
<h1>Editing team_member</h1>

<%= render 'form' %>

<%= link_to 'Show', @team_member %> |
<%= link_to 'Back', team_members_path %>

app/views/team_members/index.html.erb
<h1>Listing team_members</h1>

<table>
  <tr>
    <th>Teamid</th>
    <th>Userid</th>
    <th>Role</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @team_members.each do |team_member| %>
  <tr>
    <td><%= team_member.teamID %></td>
    <td><%= team_member.userID %></td>
    <td><%= team_member.role %></td>
    <td><%= link_to 'Show', team_member %></td>
    <td><%= link_to 'Edit', edit_team_member_path(team_member) %></td>
    <td><%= link_to 'Destroy', team_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Team member', new_team_member_path %>

app/views/team_members/new.html.erb
<h1>New team_member</h1>

<%= render 'form' %>

<%= link_to 'Back', team_members_path %>

app/views/team_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Teamid:</b>
  <%= @team_member.teamID %>
</p>

<p>
  <b>Userid:</b>
  <%= @team_member.userID %>
</p>

<p>
  <b>Role:</b>
  <%= @team_member.role %>
</p>


<%= link_to 'Edit', edit_team_member_path(@team_member) %> |
<%= link_to 'Back', team_members_path %>