config/routes.rb
TeamTracker::Application.routes.draw do
  resources :team_members

  resources :teams

  resources :contacts

  devise_for :users

  get "home/index"
  get "devise/new"

  resources :users
  
  match 'contacts/:id/edit2' => 'contacts#edit2'
  

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :dateOfBirth, :eMailAddress, :facebookCredentials, :firstName, :hobbies, :lastAccessDateTime, :lastName, :parent, :password, :state, :twitterCredentials, :verifed, :website

  #has_and_belongs_to_many :contacts
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        #format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.html { redirect_to edit_user_path(current_user.id), notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
   <!-- <strong><%= @user.email %><br /></strong> -->
  </div>  
  <div style="margin: 20px">
  <!-- <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :verifed %><br />
    <%= f.check_box :verifed %>
  </div>
  <div class="field">
    <%= f.label :parent %><br />
    <%= f.check_box :parent %>
  </div>
  <div class="field">
    <%= f.label :facebookCredentials %><br />
    <%= f.text_field :facebookCredentials %>
  </div>
  <div class="field">
    <%= f.label :twitterCredentials %><br />
    <%= f.text_field :twitterCredentials %>
  </div> -->
  <div class="field">
    <%= f.label :firstName %><br />
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br />
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :dateOfBirth %><br />
    <%= f.date_select :dateOfBirth, :start_year => 1950, :end_year => 2010 %>
    <!--<%= f.date_select :dateOfBirth %>-->
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :hobbies %><br />
    <%= f.text_field :hobbies %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <!-- <div class="field">
    <%= f.label :lastAccessDateTime %><br />
    <%= f.datetime_select :lastAccessDateTime %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
    <input type="reset">
  </div>
  <p id="notice"><%= notice %> &nbsp;</p>
</div>
  <div style="text-align: center;">
    <h4>
      <%= link_to 'Go Back', home_index_path(current_user.id) %>
    </h4>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 style="margin-top: 35px; clear:left;">Update Profile</h1>

<%= render 'form' %>

<!-- <%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %> -->

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Emailaddress</th>
    <th>Password</th>
    <th>Verifed</th>
    <th>Parent</th>
    <th>Facebookcredentials</th>
    <th>Twittercredentials</th>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Dateofbirth</th>
    <th>State</th>
    <th>Hobbies</th>
    <th>Website</th>
    <th>Lastaccessdatetime</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.eMailAddress %></td>
    <td><%= user.password %></td>
    <td><%= user.verifed %></td>
    <td><%= user.parent %></td>
    <td><%= user.facebookCredentials %></td>
    <td><%= user.twitterCredentials %></td>
    <td><%= user.firstName %></td>
    <td><%= user.lastName %></td>
    <td><%= user.dateOfBirth %></td>
    <td><%= user.state %></td>
    <td><%= user.hobbies %></td>
    <td><%= user.website %></td>
    <td><%= user.lastAccessDateTime %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<!--<p>
  <b><%= @user.email %></b>
</p>-->

<!-- <p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Verifed:</b>
  <%= @user.verifed %>
</p>

<p>
  <b>Parent:</b>
  <%= @user.parent %>
</p>

<p>
  <b>Facebookcredentials:</b>
  <%= @user.facebookCredentials %>
</p>

<p>
  <b>Twittercredentials:</b>
  <%= @user.twitterCredentials %>
</p> -->

<p style="margin-top: 35px; clear:left;">
  <b>Firstname:</b>
  <%= @user.firstName %>
</p>

<p>
  <b>Lastname:</b>
  <%= @user.lastName %>
</p>

<p>
  <b>Dateofbirth:</b>
  <%= @user.dateOfBirth %>
</p>

<p>
  <b>State:</b>
  <%= @user.state %>
</p>

<p>
  <b>Hobbies:</b>
  <%= @user.hobbies %>
</p>

<p>
  <b>Website:</b>
  <%= @user.website %>
</p>

<!-- <p>
  <b>Lastaccessdatetime:</b>
  <%= @user.lastAccessDateTime %>
</p> -->


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', root_path%>