config/routes.rb
TeamTracker::Application.routes.draw do
  resources :team_members

  resources :teams

  resources :contacts

  devise_for :users

  get "home/index"
  get "devise/new"

  resources :users
  
  match 'contacts/:id/edit2' => 'contacts#edit2'
  

  root :to => 'home#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :userID, :eMail, :firstName, :lastName

  #validates_format_of :eMail, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i

  #has_and_belongs_to_many :users
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    redirect_to edit_contact_path(current_user.id)
    #@contact = Contact.find(params[:id])

    #respond_to do |format|
    #  format.html # show.html.erb
    #  format.json { render json: @contact }
    #end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    #@contact = Contact.find(params[:id])
    @user = User.find(params[:id])
    @contacts = Contact.find_all_by_userID(params[:id])
    @contact = Contact.new
    #@contacts = Contact.joins('INNER JOIN users ON users.id = contacts.userContactID').where('contacts.userID' => params[:id])
    #Client.joins('LEFT OUTER JOIN addresses ON addresses.client_id = clients.id')


    respond_to do |format|
      format.html # edit.html.erb
      format.json { render json: @contacts }
    end
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to edit_contact_path(current_user.id), notice: 'Contact was successfully created.' }
        #format.html { render action: "edit",  notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        #format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.html { redirect_to edit_contact_path(current_user.id), notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to edit_contact_path(current_user.id) }
      format.json { head :no_content }
    end
  end

  def edit2
    @contact = Contact.find(params[:id])
    @user = User.find(current_user.id)

    #@user = User.find(params[:id])
    #@contacts = Contact.find_all_by_userID(params[:id])
    #@contact = Contact.new
    #@contacts = Contact.joins('INNER JOIN users ON users.id = contacts.userContactID').where('contacts.userID' => params[:id])
    #Client.joins('LEFT OUTER JOIN addresses ON addresses.client_id = clients.id')


    respond_to do |format|
      format.html # edit.html.erb
      format.json { render json: @contacts }
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
  <!--<p id="notice"><%= flash[:notice] %></p>-->
  <div class="user">
    <!--<%= @user.email %>-->
    <!--<br>
    <%= @user.id %>-->
  </div>

  <div class="show-contacts">
    <% if @contacts.any? %>
     <!--<%= @contacts.size %>-->
    <table style="margin: 20px; padding: 20px; border: 1px; border-style: solid;">
      <tr>
        <!--<th>Userid</th>-->
        <th style="min-width: 150px">Email</th>
        <th style="min-width: 100px">First Name</th>
        <th style="min-width: 100px">Last Name</th>
        <th></th>
        <th></th>
      </tr>
    <% @contacts.each do |con| %>
      <tr>
        <!--<td><%= con.userID %></td>-->
        <td style="min-width: 150px"><%= con.eMail %></td>
        <td style="min-width: 100px"><%= con.firstName %></td>
        <td style="min-width: 100px"><%= con.lastName %></td>
        <td style="padding-left: 20px"><%= link_to 'Edit', :controller => 'contacts', :action => 'edit2', :id => con.id %></td>
        <td><%= link_to 'Delete', con, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
  <% end %>
  </div>

<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="add-contacts" style="margin: 20px;">
    <div class="section-header">
      <h3>Add a new Contact</h3>
    </div>  
    <div class="field">
      <%= f.label :eMail %><br />
      <%= f.email_field :eMail %>
    </div>    
    <div class="field">
      <%= f.label :firstName %><br />
      <%= f.text_field :firstName %>
    </div>
    <div class="field">
      <%= f.label :lastName %><br />
      <%= f.text_field :lastName %>
    </div>
        <div class="field">
        <input type="hidden" name="contact[userID]" value="<%= @user.id %>" />
    </div>
      <div class="actions">
    <%= f.submit %>
    <input type="reset">
    <!--<%= link_to 'Home', '/' %> -->
  </div>
  </div>
  <div style="text-align: center;">
    <h4>
      <%= link_to 'Go Back', home_index_path(current_user.id) %>
    </h4>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1 style="margin-top: 35px; clear:left;">Contacts</h1>

<%= render 'form' %>

<!--<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>-->

app/views/contacts/edit2.html.erb
<div style="margin-top: 35px; clear:left;">
  <h1>Update Contact</h1>
  <div style="margin: 20px; padding: 20px; border: 1px; border-style: solid;">
<%= form_for(@contact) do |f| %> <!-- #, :url => {:action => 'edit', :id => current_user.id} -->
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :eMail %><br />
    <%= f.text_field :eMail %>
  </div>
  <div class="field">
    <%= f.label :firstName %><br />
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br />
    <%= f.text_field :lastName %>
  </div>  
  <div class="actions">
    <%= f.submit %>
    <input type="reset">
  </div>
<% end %>
</div>
  <div style="text-align: center;">
    <h4>
      <%= link_to 'Go Back', edit_contact_path(current_user.id) %>
    </h4>
  </div>
</div>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <tr>
    <th>Userid</th>
    <th>Usercontactid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.userID %></td>
    <td><%= contact.userContactID %></td>
    <td><%= link_to 'Show', contact %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
    <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Userid:</b>
  <%= @contact.userID %>
</p>

<p>
  <b>Usercontactid:</b>
  <%= @contact.eMail %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>