config/routes.rb
TeamTracker::Application.routes.draw do
  resources :team_members

  resources :teams

  resources :contacts

  devise_for :users

  get "home/index"
  get "devise/new"

  resources :users
  
  match 'contacts/:id/edit2' => 'contacts#edit2'
  

  root :to => 'home#index'

end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
	- if msg.is_a?(String)
		%div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
			%a.close{"data-dismiss" => "alert"} ×
			= content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Home", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to('Teams', teams_path)

    %li
      = link_to('Logout', destroy_user_session_path, :method=>'delete')
  - else
    %li
      = link_to('Login', new_user_session_path)
  - if user_signed_in?
    %li
      = link_to('Edit account', edit_user_registration_path)
  - else
    %li
      = link_to('Sign up', new_user_registration_path)

app/views/layouts/application.html.haml
!!!
%html
   %head
      %meta{:charset => "utf-8"}
      %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
      %title= content_for?(:title) ? yield(:title) : "Team Tracker"
      = stylesheet_link_tag "application", :media => "all"
      = javascript_include_tag "application"
      = csrf_meta_tags
      = yield(:head)
%body{:style => "width: 1000px;"}
   %div{:class => "header-image"}
      %img{:src => "/assets/smartsheet.PNG"}
   %div{:class => "session-info"}
      %h4{:style => "float: left; padding-top: -5px; margin-top: -5px"}
         = link_to('Home', home_index_path)
      - if user_signed_in?
         %span{:class => "logout", :style => "float: right;"}
            = @user.email
            (
            = link_to('Logout', destroy_user_session_path, :method => :delete)
            )
   #main{:role => "main"}
      .container
         .content
            .row
               .span12
                  -#= render 'layouts/messages'
                  = yield
   %footer
      %h4{:style => "text-align: center;"}
         -#= link_to_unless_current('Go Home', home_index_path)